[tool.poetry]
name = "ftb-password-changer"
version = "0.1.0"
description = ""
authors = ["Radian LLC <contact+ftb-password-changer@radian.codes>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0.1"
levenshtein = "^0.25.1"
selenium = "^4.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
